php_variations:
  - name: cli
    default: true
  - name: fpm

php_versions:
  - major: "5"
    minor_versions:
      - minor: "5.6"
        base_os:
          - name: stretch
        patch_versions:
          - 5.6.40

operating_systems:
  - family: debian
    default: true
    versions:
      - name: "Debian Stretch"
        version: stretch
        number: 9
        nginx_version: stub
